from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(575, 595)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.main_grid = QtWidgets.QGridLayout()
        self.main_grid.setObjectName("main_grid")
        self.side_layout = QtWidgets.QWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.side_layout.setFont(font)
        self.side_layout.setStyleSheet("#side_layout{background: rgb(230, 231, 255);}")
        self.side_layout.setObjectName("side_layout")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.side_layout)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.formLayout_8 = QtWidgets.QFormLayout()
        self.formLayout_8.setObjectName("formLayout_8")
        self.gridLayout_21 = QtWidgets.QGridLayout()
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.side_input_1 = QtWidgets.QCheckBox(self.side_layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.side_input_1.sizePolicy().hasHeightForWidth())
        self.side_input_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.side_input_1.setFont(font)
        self.side_input_1.setText("")
        self.side_input_1.setCheckable(True)
        self.side_input_1.setObjectName("side_input_1")
        self.gridLayout_21.addWidget(self.side_input_1, 0, 1, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.side_layout)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_57.setFont(font)
        self.label_57.setToolTip("<html><head/><body><p>If you <span style=\" font-weight:600;\">check</span> it, all the <span style=\" font-weight:600;\">files</span> under the <span style=\" font-weight:600;\">subfolders</span> will be also renamed.</p></body></html>")
        self.label_57.setText("Include Subfolders  : ")
        self.label_57.setObjectName("label_57")
        self.gridLayout_21.addWidget(self.label_57, 0, 0, 1, 1)
        self.formLayout_8.setLayout(0, QtWidgets.QFormLayout.SpanningRole, self.gridLayout_21)
        self.label_46 = QtWidgets.QLabel(self.side_layout)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_46.setFont(font)
        self.label_46.setToolTip("<html><head/><body><p>Here, you can find <span style=\" font-weight:600;\">settings</span> for selecting only those file which are <span style=\" font-weight:600;\">allowed</span>. Leave any option <span style=\" font-weight:600;\">blank</span> if you do not need them.</p></body></html>")
        self.label_46.setText("<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Only Allow Files</span></p></body></html>")
        self.label_46.setObjectName("label_46")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.label_46)
        self.label_51 = QtWidgets.QLabel(self.side_layout)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_51.setFont(font)
        self.label_51.setToolTip("<html><head/><body><p>If you <span style=\" font-weight:600;\">enable</span> it and change any setting bellow, <span style=\" font-weight:600;\">only allow system</span> will work. If a file is <span style=\" font-weight:600;\">not allowed</span>, it will not  be <span style=\" font-weight:600;\">renamed</span>.</p></body></html>")
        self.label_51.setText("Enabled :")
        self.label_51.setObjectName("label_51")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_51)
        self.side_input_2 = QtWidgets.QCheckBox(self.side_layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.side_input_2.sizePolicy().hasHeightForWidth())
        self.side_input_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.side_input_2.setFont(font)
        self.side_input_2.setText("")
        self.side_input_2.setCheckable(True)
        self.side_input_2.setObjectName("side_input_2")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.side_input_2)
        self.widget_0_1 = QtWidgets.QWidget(self.side_layout)
        self.widget_0_1.setEnabled(False)
        self.widget_0_1.setObjectName("widget_0_1")
        self.formLayout = QtWidgets.QFormLayout(self.widget_0_1)
        self.formLayout.setContentsMargins(0, 3, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_44 = QtWidgets.QLabel(self.widget_0_1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_44.setFont(font)
        self.label_44.setToolTip("<html><head/><body><p><span style=\" font-weight:600;\">Check</span> it, if you want to <span style=\" font-weight:600;\">allow</span> only those file which <span style=\" font-weight:600;\">does not </span>have any <span style=\" font-weight:600;\">extension</span>.</p></body></html>")
        self.label_44.setText("With no ext : ")
        self.label_44.setObjectName("label_44")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_44)
        self.side_input_3 = QtWidgets.QCheckBox(self.widget_0_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.side_input_3.sizePolicy().hasHeightForWidth())
        self.side_input_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.side_input_3.setFont(font)
        self.side_input_3.setText("")
        self.side_input_3.setCheckable(True)
        self.side_input_3.setObjectName("side_input_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.side_input_3)
        self.gridLayout_20 = QtWidgets.QGridLayout()
        self.gridLayout_20.setHorizontalSpacing(0)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.label_55 = QtWidgets.QLabel(self.widget_0_1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_55.setFont(font)
        self.label_55.setToolTip("<html><head/><body><p>Use it, if you want to <span style=\" font-weight:600;\">allow</span> only those file which have any of the following <span style=\" font-weight:600;\">extension</span>.</p><p>Here you can set <span style=\" font-weight:600;\">more than one</span> extension by putting <span style=\" font-weight:600;\">&quot;|&quot;(Pipe) </span>between them.</p></body></html>")
        self.label_55.setText("With ext : ")
        self.label_55.setObjectName("label_55")
        self.gridLayout_20.addWidget(self.label_55, 0, 0, 1, 1)
        self.side_input_4 = QtWidgets.QLineEdit(self.widget_0_1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.side_input_4.setFont(font)
        self.side_input_4.setObjectName("side_input_4")
        self.gridLayout_20.addWidget(self.side_input_4, 0, 1, 1, 1)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.SpanningRole, self.gridLayout_20)
        self.label_54 = QtWidgets.QLabel(self.widget_0_1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_54.setFont(font)
        self.label_54.setToolTip("<html><head/><body><p>Use it, if you want to <span style=\" font-weight:600;\">allow</span> only those file which have any of the following <span style=\" font-weight:600;\">text </span>on the <span style=\" font-weight:600;\">start</span> of the filename (without extension).</p><p>Here you can set <span style=\" font-weight:600;\">more than one</span> text by putting <span style=\" font-weight:600;\">&quot;|&quot;(Pipe) </span>between them.</p></body></html>")
        self.label_54.setText("Has on start  : ")
        self.label_54.setObjectName("label_54")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_54)
        self.side_input_5 = QtWidgets.QLineEdit(self.widget_0_1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.side_input_5.setFont(font)
        self.side_input_5.setObjectName("side_input_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.side_input_5)
        self.label_53 = QtWidgets.QLabel(self.widget_0_1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_53.setFont(font)
        self.label_53.setToolTip("<html><head/><body><p>Use it, if you want to <span style=\" font-weight:600;\">allow</span> only those file which have any of the following <span style=\" font-weight:600;\">text </span>on the <span style=\" font-weight:600;\">end</span> of the filename (without extension).</p><p>Here you can set <span style=\" font-weight:600;\">more than one</span> text by putting <span style=\" font-weight:600;\">&quot;|&quot;(Pipe) </span>between them.</p></body></html>")
        self.label_53.setText("Has on end  : ")
        self.label_53.setObjectName("label_53")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_53)
        self.side_input_6 = QtWidgets.QLineEdit(self.widget_0_1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.side_input_6.setFont(font)
        self.side_input_6.setObjectName("side_input_6")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.side_input_6)
        self.label_52 = QtWidgets.QLabel(self.widget_0_1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_52.setFont(font)
        self.label_52.setToolTip("<html><head/><body><p>Use it, if you want to <span style=\" font-weight:600;\">allow</span> only those file which have any of the following <span style=\" font-weight:600;\">text </span>in the filename (without extension).</p><p>Here you can set <span style=\" font-weight:600;\">more than one</span> text by putting <span style=\" font-weight:600;\">&quot;|&quot;(Pipe) </span>between them.</p></body></html>")
        self.label_52.setText("Has string  : ")
        self.label_52.setObjectName("label_52")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_52)
        self.side_input_7 = QtWidgets.QLineEdit(self.widget_0_1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.side_input_7.setFont(font)
        self.side_input_7.setObjectName("side_input_7")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.side_input_7)
        self.formLayout_8.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.widget_0_1)
        self.gridLayout_3.addLayout(self.formLayout_8, 2, 0, 1, 1)
        self.txt_stat = QtWidgets.QLabel(self.side_layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_stat.sizePolicy().hasHeightForWidth())
        self.txt_stat.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txt_stat.setFont(font)
        self.txt_stat.setAcceptDrops(True)
        self.txt_stat.setToolTip("<html><head/><body><p>Here, you will see the <span style=\" font-weight:600;\">current number</span> of the<span style=\" font-weight:600;\"> selected folders</span>. You can also <span style=\" font-weight:600;\">drag</span> your <span style=\" font-weight:600;\">folders</span> here to select.</p></body></html>")
        self.txt_stat.setStyleSheet("QLabel{background-color: rgb(234, 255, 238); border: 1px solid gray; padding: 5px;}")
        self.txt_stat.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_stat.setObjectName("txt_stat")
        self.gridLayout_3.addWidget(self.txt_stat, 0, 0, 1, 1)
        self.bt_main_menu = QtWidgets.QPushButton(self.side_layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_main_menu.sizePolicy().hasHeightForWidth())
        self.bt_main_menu.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Candara")
        font.setPointSize(14)
        self.bt_main_menu.setFont(font)
        self.bt_main_menu.setText("Main Menu")
        self.bt_main_menu.setObjectName("bt_main_menu")
        self.gridLayout_3.addWidget(self.bt_main_menu, 4, 0, 1, 1)
        self.formLayout_7 = QtWidgets.QFormLayout()
        self.formLayout_7.setObjectName("formLayout_7")
        self.label_41 = QtWidgets.QLabel(self.side_layout)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_41.setFont(font)
        self.label_41.setToolTip("<html><head/><body><p>Here, you can find <span style=\" font-weight:600;\">settings</span> for ignoring a file. Leave any option <span style=\" font-weight:600;\">blank</span> if you do not need them.</p></body></html>")
        self.label_41.setText("<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Ignore Files</span></p></body></html>")
        self.label_41.setObjectName("label_41")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_41)
        self.label_56 = QtWidgets.QLabel(self.side_layout)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_56.setFont(font)
        self.label_56.setToolTip("<html><head/><body><p>If you <span style=\" font-weight:600;\">enable</span> it and change any setting bellow,<span style=\" font-weight:600;\"> ignore system</span> will work. If a file is <span style=\" font-weight:600;\">ignored</span>, it wiil not be <span style=\" font-weight:600;\">renamed</span>.</p></body></html>")
        self.label_56.setText("Enabled :")
        self.label_56.setObjectName("label_56")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_56)
        self.side_input_8 = QtWidgets.QCheckBox(self.side_layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.side_input_8.sizePolicy().hasHeightForWidth())
        self.side_input_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.side_input_8.setFont(font)
        self.side_input_8.setText("")
        self.side_input_8.setCheckable(True)
        self.side_input_8.setObjectName("side_input_8")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.side_input_8)
        self.widget_0_2 = QtWidgets.QWidget(self.side_layout)
        self.widget_0_2.setEnabled(False)
        self.widget_0_2.setObjectName("widget_0_2")
        self.formLayout_5 = QtWidgets.QFormLayout(self.widget_0_2)
        self.formLayout_5.setContentsMargins(0, 3, 0, 0)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_42 = QtWidgets.QLabel(self.widget_0_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_42.setFont(font)
        self.label_42.setToolTip("<html><head/><body><p><span style=\" font-weight:600;\">Check</span> it, if you want to <span style=\" font-weight:600;\">ignore</span> those file which <span style=\" font-weight:600;\">does not </span>have any <span style=\" font-weight:600;\">extension</span>.</p></body></html>")
        self.label_42.setText("With no ext : ")
        self.label_42.setObjectName("label_42")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_42)
        self.side_input_9 = QtWidgets.QCheckBox(self.widget_0_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.side_input_9.sizePolicy().hasHeightForWidth())
        self.side_input_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.side_input_9.setFont(font)
        self.side_input_9.setText("")
        self.side_input_9.setCheckable(True)
        self.side_input_9.setObjectName("side_input_9")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.side_input_9)
        self.gridLayout_18 = QtWidgets.QGridLayout()
        self.gridLayout_18.setHorizontalSpacing(0)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.label_43 = QtWidgets.QLabel(self.widget_0_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_43.setFont(font)
        self.label_43.setToolTip("<html><head/><body><p>Use it, if you want to <span style=\" font-weight:600;\">ignore</span> those file which have any of the following <span style=\" font-weight:600;\">extension</span>.</p><p>Here you can set <span style=\" font-weight:600;\">more than one</span> extension by putting <span style=\" font-weight:600;\">&quot;|&quot;(Pipe) </span>between them.</p></body></html>")
        self.label_43.setText("With ext : ")
        self.label_43.setObjectName("label_43")
        self.gridLayout_18.addWidget(self.label_43, 0, 0, 1, 1)
        self.side_input_10 = QtWidgets.QLineEdit(self.widget_0_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.side_input_10.setFont(font)
        self.side_input_10.setObjectName("side_input_10")
        self.gridLayout_18.addWidget(self.side_input_10, 0, 1, 1, 1)
        self.formLayout_5.setLayout(1, QtWidgets.QFormLayout.SpanningRole, self.gridLayout_18)
        self.label_47 = QtWidgets.QLabel(self.widget_0_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_47.setFont(font)
        self.label_47.setToolTip("<html><head/><body><p>Use it, if you want to <span style=\" font-weight:600;\">ignore</span> those file which have any of the following <span style=\" font-weight:600;\">text </span>on the <span style=\" font-weight:600;\">start</span> of the filename (without extension).</p><p>Here you can set <span style=\" font-weight:600;\">more than one</span> text by putting <span style=\" font-weight:600;\">&quot;|&quot;(Pipe) </span>between them.</p></body></html>")
        self.label_47.setText("Has on start  : ")
        self.label_47.setObjectName("label_47")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_47)
        self.side_input_11 = QtWidgets.QLineEdit(self.widget_0_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.side_input_11.setFont(font)
        self.side_input_11.setObjectName("side_input_11")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.side_input_11)
        self.label_48 = QtWidgets.QLabel(self.widget_0_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_48.setFont(font)
        self.label_48.setToolTip("<html><head/><body><p>Use it, if you want to <span style=\" font-weight:600;\">ignore</span> those file which have any of the following <span style=\" font-weight:600;\">text </span>on the <span style=\" font-weight:600;\">end</span> of the filename (without extension).</p><p>Here you can set <span style=\" font-weight:600;\">more than one</span> text by putting <span style=\" font-weight:600;\">&quot;|&quot;(Pipe) </span>between them.</p></body></html>")
        self.label_48.setText("Has on end  : ")
        self.label_48.setObjectName("label_48")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_48)
        self.side_input_12 = QtWidgets.QLineEdit(self.widget_0_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.side_input_12.setFont(font)
        self.side_input_12.setObjectName("side_input_12")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.side_input_12)
        self.label_49 = QtWidgets.QLabel(self.widget_0_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_49.setFont(font)
        self.label_49.setToolTip("<html><head/><body><p>Use it, if you want to <span style=\" font-weight:600;\">ignore</span> those file which have any of the following <span style=\" font-weight:600;\">text </span>in the filename (without extension).</p><p>Here you can set <span style=\" font-weight:600;\">more than one</span> text by putting <span style=\" font-weight:600;\">&quot;|&quot;(Pipe) </span>between them.</p></body></html>")
        self.label_49.setText("Has string  : ")
        self.label_49.setObjectName("label_49")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_49)
        self.side_input_13 = QtWidgets.QLineEdit(self.widget_0_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.side_input_13.setFont(font)
        self.side_input_13.setObjectName("side_input_13")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.side_input_13)
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.widget_0_2)
        self.gridLayout_3.addLayout(self.formLayout_7, 3, 0, 1, 1)
        self.main_grid.addWidget(self.side_layout, 0, 0, 1, 1)
        self.main_layout = QtWidgets.QWidget(self.centralwidget)
        self.main_layout.setStyleSheet("#main_layout{background: rgb(248, 231, 255);}")
        self.main_layout.setObjectName("main_layout")
        self.gridLayout = QtWidgets.QGridLayout(self.main_layout)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.main_layout)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_0 = QtWidgets.QWidget()
        self.page_0.setObjectName("page_0")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page_0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.choose_layout = QtWidgets.QWidget(self.page_0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.choose_layout.sizePolicy().hasHeightForWidth())
        self.choose_layout.setSizePolicy(sizePolicy)
        self.choose_layout.setMaximumSize(QtCore.QSize(360, 16777215))
        self.choose_layout.setStyleSheet("")
        self.choose_layout.setObjectName("choose_layout")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.choose_layout)
        self.gridLayout_6.setVerticalSpacing(12)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_2 = QtWidgets.QLabel(self.choose_layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setText("4 Defferents category")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_6.addWidget(self.label_2, 1, 0, 1, 1)
        self.bt_menu_3 = QtWidgets.QPushButton(self.choose_layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_menu_3.sizePolicy().hasHeightForWidth())
        self.bt_menu_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(16)
        self.bt_menu_3.setFont(font)
        self.bt_menu_3.setText("Serealize")
        self.bt_menu_3.setObjectName("bt_menu_3")
        self.gridLayout_6.addWidget(self.bt_menu_3, 5, 0, 1, 1)
        self.bt_menu_4 = QtWidgets.QPushButton(self.choose_layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_menu_4.sizePolicy().hasHeightForWidth())
        self.bt_menu_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(16)
        self.bt_menu_4.setFont(font)
        self.bt_menu_4.setText("Name Fixer")
        self.bt_menu_4.setObjectName("bt_menu_4")
        self.gridLayout_6.addWidget(self.bt_menu_4, 6, 0, 1, 1)
        self.label_1 = QtWidgets.QLabel(self.choose_layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_1.sizePolicy().hasHeightForWidth())
        self.label_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_1.setFont(font)
        self.label_1.setText("Choose Your Work")
        self.label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1.setObjectName("label_1")
        self.gridLayout_6.addWidget(self.label_1, 0, 0, 1, 1)
        self.bt_menu_2 = QtWidgets.QPushButton(self.choose_layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_menu_2.sizePolicy().hasHeightForWidth())
        self.bt_menu_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(16)
        self.bt_menu_2.setFont(font)
        self.bt_menu_2.setText("Suffix Prefix")
        self.bt_menu_2.setObjectName("bt_menu_2")
        self.gridLayout_6.addWidget(self.bt_menu_2, 3, 0, 1, 1)
        self.bt_menu_1 = QtWidgets.QPushButton(self.choose_layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_menu_1.sizePolicy().hasHeightForWidth())
        self.bt_menu_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(16)
        self.bt_menu_1.setFont(font)
        self.bt_menu_1.setText("Change Extension")
        self.bt_menu_1.setObjectName("bt_menu_1")
        self.gridLayout_6.addWidget(self.bt_menu_1, 2, 0, 1, 1)
        self.gridLayout_5.addWidget(self.choose_layout, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_0)
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.rn_layout_1 = QtWidgets.QWidget(self.page_1)
        self.rn_layout_1.setStyleSheet("")
        self.rn_layout_1.setObjectName("rn_layout_1")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.rn_layout_1)
        self.gridLayout_7.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout_7.setContentsMargins(5, -1, 5, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_4 = QtWidgets.QLabel(self.rn_layout_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setText("Change Extension")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_7.addWidget(self.label_4, 0, 0, 1, 1)
        self.formLayout_1 = QtWidgets.QFormLayout()
        self.formLayout_1.setContentsMargins(-1, 15, -1, 15)
        self.formLayout_1.setObjectName("formLayout_1")
        self.widget_1_1 = QtWidgets.QWidget(self.rn_layout_1)
        self.widget_1_1.setObjectName("widget_1_1")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.widget_1_1)
        self.gridLayout_11.setContentsMargins(0, 2, 0, 0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_5 = QtWidgets.QLabel(self.widget_1_1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setToolTip("<html><head/><body><p>Write here the <span style=\" font-weight:600;\">extension </span><span style=\" font-size:7pt;\">(without dot)</span> that you want to set in your selected files.</p></body></html>")
        self.label_5.setText("Wanted Extension (without dot)* : ")
        self.label_5.setObjectName("label_5")
        self.gridLayout_11.addWidget(self.label_5, 0, 0, 1, 1)
        self.rn_1_input_2 = QtWidgets.QLineEdit(self.widget_1_1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.rn_1_input_2.setFont(font)
        self.rn_1_input_2.setObjectName("rn_1_input_2")
        self.gridLayout_11.addWidget(self.rn_1_input_2, 0, 1, 1, 1)
        self.formLayout_1.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.widget_1_1)
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_50 = QtWidgets.QLabel(self.rn_layout_1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_50.setFont(font)
        self.label_50.setToolTip("<html><head/><body><p><span style=\" font-weight:600;\">Select</span> your <span style=\" font-weight:600;\">work</span> from here.</p></body></html>")
        self.label_50.setText("Action : ")
        self.label_50.setObjectName("label_50")
        self.gridLayout_12.addWidget(self.label_50, 0, 0, 1, 1)
        self.rn_1_input_1 = QtWidgets.QComboBox(self.rn_layout_1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rn_1_input_1.setFont(font)
        self.rn_1_input_1.setCurrentText("Change Extension")
        self.rn_1_input_1.setObjectName("rn_1_input_1")
        self.rn_1_input_1.addItem("")
        self.rn_1_input_1.setItemText(0, "Change Extension")
        self.rn_1_input_1.addItem("")
        self.rn_1_input_1.setItemText(1, "Add Extension")
        self.rn_1_input_1.addItem("")
        self.rn_1_input_1.setItemText(2, "Remove Extension")
        self.gridLayout_12.addWidget(self.rn_1_input_1, 0, 1, 1, 1)
        self.formLayout_1.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.gridLayout_12)
        self.gridLayout_7.addLayout(self.formLayout_1, 2, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.rn_layout_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setText("Please, complete this form")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_7.addWidget(self.label_3, 1, 0, 1, 1)
        self.bt_reset_1 = QtWidgets.QPushButton(self.rn_layout_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_reset_1.sizePolicy().hasHeightForWidth())
        self.bt_reset_1.setSizePolicy(sizePolicy)
        self.bt_reset_1.setText("")
        self.bt_reset_1.setIconSize(QtCore.QSize(32, 32))
        self.bt_reset_1.setFlat(True)
        self.bt_reset_1.setObjectName("bt_reset_1")
        self.gridLayout_7.addWidget(self.bt_reset_1, 0, 1, 2, 1)
        self.bt_rename_1 = QtWidgets.QPushButton(self.rn_layout_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_rename_1.sizePolicy().hasHeightForWidth())
        self.bt_rename_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Andalus")
        font.setPointSize(16)
        self.bt_rename_1.setFont(font)
        self.bt_rename_1.setText("Rename")
        self.bt_rename_1.setObjectName("bt_rename_1")
        self.gridLayout_7.addWidget(self.bt_rename_1, 3, 0, 1, 2)
        self.gridLayout_7.setRowStretch(0, 1)
        self.gridLayout_4.addWidget(self.rn_layout_1, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.rn_layout_2 = QtWidgets.QWidget(self.page_2)
        self.rn_layout_2.setStyleSheet("")
        self.rn_layout_2.setObjectName("rn_layout_2")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.rn_layout_2)
        self.gridLayout_8.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout_8.setContentsMargins(5, -1, 5, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_8 = QtWidgets.QLabel(self.rn_layout_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setText("Please, complete this form")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_8.addWidget(self.label_8, 1, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.rn_layout_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_9.setFont(font)
        self.label_9.setText("Suffix Prefix")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_8.addWidget(self.label_9, 0, 0, 1, 1)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setContentsMargins(-1, 15, -1, 15)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_10 = QtWidgets.QLabel(self.rn_layout_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setToolTip("<html><head/><body><p>Type here the <span style=\" font-weight:600;\">prefix</span> that you want to set. Leave it <span style=\" font-weight:600;\">blank</span> if you do not want it.</p></body></html>")
        self.label_10.setText("Add Prefix : ")
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.rn_2_input_1 = QtWidgets.QLineEdit(self.rn_layout_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.rn_2_input_1.setFont(font)
        self.rn_2_input_1.setObjectName("rn_2_input_1")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.rn_2_input_1)
        self.label_11 = QtWidgets.QLabel(self.rn_layout_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setToolTip("<html><head/><body><p>Type here the <span style=\" font-weight:600;\">suffix</span> that you want to set. Leave it <span style=\" font-weight:600;\">blank</span> if you do not want it.</p></body></html>")
        self.label_11.setText("Add Suffix : ")
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.rn_2_input_2 = QtWidgets.QLineEdit(self.rn_layout_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.rn_2_input_2.setFont(font)
        self.rn_2_input_2.setObjectName("rn_2_input_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.rn_2_input_2)
        self.gridLayout_19 = QtWidgets.QGridLayout()
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.label_36 = QtWidgets.QLabel(self.rn_layout_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_36.setFont(font)
        self.label_36.setToolTip("<html><head/><body><p>If it is checked, new name will be: <span style=\" font-weight:600;\">prefix +filename + suffix + extension</span>.</p><p>Otherwise, <span style=\" font-weight:600;\">extension</span> will not be replaced and new name will be: <span style=\" font-weight:600;\">prefix +  full filename + suffix</span>.</p></body></html>")
        self.label_36.setText("Don\'t Change extension : ")
        self.label_36.setObjectName("label_36")
        self.gridLayout_19.addWidget(self.label_36, 0, 0, 1, 1)
        self.rn_2_input_3 = QtWidgets.QCheckBox(self.rn_layout_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rn_2_input_3.sizePolicy().hasHeightForWidth())
        self.rn_2_input_3.setSizePolicy(sizePolicy)
        self.rn_2_input_3.setText("")
        self.rn_2_input_3.setChecked(True)
        self.rn_2_input_3.setObjectName("rn_2_input_3")
        self.gridLayout_19.addWidget(self.rn_2_input_3, 0, 1, 1, 1)
        self.formLayout_2.setLayout(2, QtWidgets.QFormLayout.SpanningRole, self.gridLayout_19)
        self.gridLayout_8.addLayout(self.formLayout_2, 2, 0, 1, 2)
        self.bt_rename_2 = QtWidgets.QPushButton(self.rn_layout_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_rename_2.sizePolicy().hasHeightForWidth())
        self.bt_rename_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Andalus")
        font.setPointSize(16)
        self.bt_rename_2.setFont(font)
        self.bt_rename_2.setText("Rename")
        self.bt_rename_2.setObjectName("bt_rename_2")
        self.gridLayout_8.addWidget(self.bt_rename_2, 3, 0, 1, 2)
        self.bt_reset_2 = QtWidgets.QPushButton(self.rn_layout_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_reset_2.sizePolicy().hasHeightForWidth())
        self.bt_reset_2.setSizePolicy(sizePolicy)
        self.bt_reset_2.setText("")
        self.bt_reset_2.setIconSize(QtCore.QSize(32, 32))
        self.bt_reset_2.setFlat(True)
        self.bt_reset_2.setObjectName("bt_reset_2")
        self.gridLayout_8.addWidget(self.bt_reset_2, 0, 1, 2, 1)
        self.gridLayout_8.setRowStretch(0, 1)
        self.gridLayout_2.addWidget(self.rn_layout_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.rn_layout_3 = QtWidgets.QWidget(self.page_3)
        self.rn_layout_3.setStyleSheet("")
        self.rn_layout_3.setObjectName("rn_layout_3")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.rn_layout_3)
        self.gridLayout_9.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout_9.setContentsMargins(5, -1, 5, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.bt_rename_3 = QtWidgets.QPushButton(self.rn_layout_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_rename_3.sizePolicy().hasHeightForWidth())
        self.bt_rename_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Andalus")
        font.setPointSize(16)
        self.bt_rename_3.setFont(font)
        self.bt_rename_3.setText("Rename")
        self.bt_rename_3.setObjectName("bt_rename_3")
        self.gridLayout_9.addWidget(self.bt_rename_3, 3, 0, 1, 2)
        self.label_12 = QtWidgets.QLabel(self.rn_layout_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setText("Please, complete this form")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_9.addWidget(self.label_12, 1, 0, 1, 1)
        self.bt_reset_3 = QtWidgets.QPushButton(self.rn_layout_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_reset_3.sizePolicy().hasHeightForWidth())
        self.bt_reset_3.setSizePolicy(sizePolicy)
        self.bt_reset_3.setText("")
        self.bt_reset_3.setIconSize(QtCore.QSize(32, 32))
        self.bt_reset_3.setFlat(True)
        self.bt_reset_3.setObjectName("bt_reset_3")
        self.gridLayout_9.addWidget(self.bt_reset_3, 0, 1, 2, 1)
        self.label_15 = QtWidgets.QLabel(self.rn_layout_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_15.setFont(font)
        self.label_15.setText("Serialize")
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_9.addWidget(self.label_15, 0, 0, 1, 1)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setContentsMargins(-1, 15, -1, 15)
        self.formLayout_3.setObjectName("formLayout_3")
        self.gridLayout_23 = QtWidgets.QGridLayout()
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.rn_3_input_1 = QtWidgets.QLineEdit(self.rn_layout_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.rn_3_input_1.setFont(font)
        self.rn_3_input_1.setObjectName("rn_3_input_1")
        self.gridLayout_23.addWidget(self.rn_3_input_1, 0, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.rn_layout_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_29.setFont(font)
        self.label_29.setToolTip("<html><head/><body><p>Here, you have to spacify a <span style=\" font-weight:600;\">name format,</span> that can contain any <span style=\" font-weight:600;\">special statement</span> bordered with <span style=\" font-weight:600;\">corner key(&lt;&gt;)</span>. Ex: <span style=\" font-weight:600;\">File_&lt;no&gt;.txt</span></p></body></html>")
        self.label_29.setText("Name Format* : ")
        self.label_29.setObjectName("label_29")
        self.gridLayout_23.addWidget(self.label_29, 0, 0, 1, 1)
        self.bt_help_3_1 = QtWidgets.QToolButton(self.rn_layout_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_help_3_1.sizePolicy().hasHeightForWidth())
        self.bt_help_3_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.bt_help_3_1.setFont(font)
        self.bt_help_3_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_help_3_1.setText("?")
        self.bt_help_3_1.setObjectName("bt_help_3_1")
        self.gridLayout_23.addWidget(self.bt_help_3_1, 0, 2, 1, 1)
        self.formLayout_3.setLayout(0, QtWidgets.QFormLayout.SpanningRole, self.gridLayout_23)
        self.label_35 = QtWidgets.QLabel(self.rn_layout_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_35.setFont(font)
        self.label_35.setToolTip("<html><head/><body><p>If it is checked, then the <span style=\" font-weight:600;\">extension</span> of the fille will remain <span style=\" font-weight:600;\">unchanged</span>.</p><p>Otherwise, the <span style=\" font-weight:600;\">extension</span> will be replaced with the<span style=\" font-weight:600;\"> name format </span>beside the <span style=\" font-weight:600;\">filename</span>.</p></body></html>")
        self.label_35.setText("Don\'t Change extension : ")
        self.label_35.setObjectName("label_35")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_35)
        self.rn_3_input_2 = QtWidgets.QCheckBox(self.rn_layout_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rn_3_input_2.sizePolicy().hasHeightForWidth())
        self.rn_3_input_2.setSizePolicy(sizePolicy)
        self.rn_3_input_2.setText("")
        self.rn_3_input_2.setChecked(True)
        self.rn_3_input_2.setObjectName("rn_3_input_2")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.rn_3_input_2)
        self.label_13 = QtWidgets.QLabel(self.rn_layout_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setToolTip("<html><head/><body><p>Here, you can set how your files will be <span style=\" font-weight:600;\">shorted.</span></p></body></html>")
        self.label_13.setText("Sort : ")
        self.label_13.setObjectName("label_13")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.rn_3_input_3 = QtWidgets.QComboBox(self.rn_layout_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rn_3_input_3.setFont(font)
        self.rn_3_input_3.setCurrentText("By Name")
        self.rn_3_input_3.setObjectName("rn_3_input_3")
        self.rn_3_input_3.addItem("")
        self.rn_3_input_3.setItemText(0, "By Name")
        self.rn_3_input_3.addItem("")
        self.rn_3_input_3.setItemText(1, "By Size")
        self.rn_3_input_3.addItem("")
        self.rn_3_input_3.setItemText(2, "By Creation Date")
        self.rn_3_input_3.addItem("")
        self.rn_3_input_3.setItemText(3, "By Modification date")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.rn_3_input_3)
        self.label_14 = QtWidgets.QLabel(self.rn_layout_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_14.setFont(font)
        self.label_14.setToolTip("<html><head/><body><p>Here, you can set how your files will be <span style=\" font-weight:600;\">ordered.</span></p></body></html>")
        self.label_14.setText("Order : ")
        self.label_14.setObjectName("label_14")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.rn_3_input_4 = QtWidgets.QComboBox(self.rn_layout_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rn_3_input_4.setFont(font)
        self.rn_3_input_4.setCurrentText("Accending")
        self.rn_3_input_4.setObjectName("rn_3_input_4")
        self.rn_3_input_4.addItem("")
        self.rn_3_input_4.setItemText(0, "Accending")
        self.rn_3_input_4.addItem("")
        self.rn_3_input_4.setItemText(1, "Deccending")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.rn_3_input_4)
        self.label_26 = QtWidgets.QLabel(self.rn_layout_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_26.setFont(font)
        self.label_26.setToolTip("<html><head/><body><p>Here, you can set a <span style=\" font-weight:600;\">prefix</span> for every files.</p></body></html>")
        self.label_26.setText("Prefix  : ")
        self.label_26.setObjectName("label_26")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_26)
        self.rn_3_input_5 = QtWidgets.QLineEdit(self.rn_layout_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.rn_3_input_5.setFont(font)
        self.rn_3_input_5.setObjectName("rn_3_input_5")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.rn_3_input_5)
        self.label_28 = QtWidgets.QLabel(self.rn_layout_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_28.setFont(font)
        self.label_28.setToolTip("<html><head/><body><p>Here, you can set a <span style=\" font-weight:600;\">suffix</span> for every files.</p></body></html>")
        self.label_28.setText("Suffix : ")
        self.label_28.setObjectName("label_28")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_28)
        self.rn_3_input_6 = QtWidgets.QLineEdit(self.rn_layout_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.rn_3_input_6.setFont(font)
        self.rn_3_input_6.setObjectName("rn_3_input_6")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.rn_3_input_6)
        self.label_37 = QtWidgets.QLabel(self.rn_layout_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_37.setFont(font)
        self.label_37.setToolTip("<html><head/><body><p>if it is <span style=\" font-weight:600;\">enabled</span>, then<span style=\" font-weight:600;\"> &lt;no&gt; </span>will be counted <span style=\" font-weight:600;\">separately</span> for <span style=\" font-weight:600;\">each folder</span>.</p></body></html>")
        self.label_37.setText("Each folder system : ")
        self.label_37.setObjectName("label_37")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_37)
        self.rn_3_input_7 = QtWidgets.QCheckBox(self.rn_layout_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rn_3_input_7.sizePolicy().hasHeightForWidth())
        self.rn_3_input_7.setSizePolicy(sizePolicy)
        self.rn_3_input_7.setText("")
        self.rn_3_input_7.setChecked(True)
        self.rn_3_input_7.setObjectName("rn_3_input_7")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.rn_3_input_7)
        self.label_30 = QtWidgets.QLabel(self.rn_layout_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_30.setFont(font)
        self.label_30.setToolTip("<html><head/><body><p><span style=\" font-weight:600;\">Specify</span> a valid <span style=\" font-weight:600;\">datetime format</span> to get the <span style=\" font-weight:600;\">creation date</span> of the file in the name format. You will get the result by using <span style=\" font-weight:600;\">&lt;c_date&gt;</span> in the<span style=\" font-weight:600;\"> name format</span>.</p></body></html>")
        self.label_30.setText("Create date format : ")
        self.label_30.setObjectName("label_30")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_30)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.rn_3_input_8 = QtWidgets.QLineEdit(self.rn_layout_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.rn_3_input_8.setFont(font)
        self.rn_3_input_8.setText("%d %m %Y")
        self.rn_3_input_8.setObjectName("rn_3_input_8")
        self.horizontalLayout_2.addWidget(self.rn_3_input_8)
        self.bt_help_3_2 = QtWidgets.QToolButton(self.rn_layout_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_help_3_2.sizePolicy().hasHeightForWidth())
        self.bt_help_3_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.bt_help_3_2.setFont(font)
        self.bt_help_3_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_help_3_2.setText("?")
        self.bt_help_3_2.setObjectName("bt_help_3_2")
        self.horizontalLayout_2.addWidget(self.bt_help_3_2)
        self.formLayout_3.setLayout(7, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.label_31 = QtWidgets.QLabel(self.rn_layout_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_31.setFont(font)
        self.label_31.setToolTip("<html><head/><body><p><span style=\" font-weight:600;\">Specify</span> a valid <span style=\" font-weight:600;\">datetime format</span> to get the <span style=\" font-weight:600;\">modification date</span> of the file in the name format. You will get the result by using <span style=\" font-weight:600;\">&lt;c_date&gt;</span> in the<span style=\" font-weight:600;\"> name format</span>.</p></body></html>")
        self.label_31.setText("Modify date format : ")
        self.label_31.setObjectName("label_31")
        self.formLayout_3.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_31)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.rn_3_input_9 = QtWidgets.QLineEdit(self.rn_layout_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.rn_3_input_9.setFont(font)
        self.rn_3_input_9.setText("%d %m %Y")
        self.rn_3_input_9.setObjectName("rn_3_input_9")
        self.horizontalLayout_3.addWidget(self.rn_3_input_9)
        self.bt_help_3_3 = QtWidgets.QToolButton(self.rn_layout_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_help_3_3.sizePolicy().hasHeightForWidth())
        self.bt_help_3_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.bt_help_3_3.setFont(font)
        self.bt_help_3_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_help_3_3.setText("?")
        self.bt_help_3_3.setObjectName("bt_help_3_3")
        self.horizontalLayout_3.addWidget(self.bt_help_3_3)
        self.formLayout_3.setLayout(8, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.gridLayout_9.addLayout(self.formLayout_3, 2, 0, 1, 2)
        self.gridLayout_9.setRowStretch(0, 1)
        self.gridLayout_10.addWidget(self.rn_layout_3, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.page_4)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.rn_layout_4 = QtWidgets.QWidget(self.page_4)
        self.rn_layout_4.setStyleSheet("")
        self.rn_layout_4.setObjectName("rn_layout_4")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.rn_layout_4)
        self.gridLayout_13.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout_13.setContentsMargins(5, -1, 5, 0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.bt_rename_4 = QtWidgets.QPushButton(self.rn_layout_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_rename_4.sizePolicy().hasHeightForWidth())
        self.bt_rename_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Andalus")
        font.setPointSize(16)
        self.bt_rename_4.setFont(font)
        self.bt_rename_4.setText("Rename")
        self.bt_rename_4.setObjectName("bt_rename_4")
        self.gridLayout_13.addWidget(self.bt_rename_4, 3, 0, 1, 3)
        self.label_18 = QtWidgets.QLabel(self.rn_layout_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setText("Please, complete this form")
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_13.addWidget(self.label_18, 1, 0, 1, 2)
        self.bt_reset_4 = QtWidgets.QPushButton(self.rn_layout_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_reset_4.sizePolicy().hasHeightForWidth())
        self.bt_reset_4.setSizePolicy(sizePolicy)
        self.bt_reset_4.setText("")
        self.bt_reset_4.setIconSize(QtCore.QSize(32, 32))
        self.bt_reset_4.setFlat(True)
        self.bt_reset_4.setObjectName("bt_reset_4")
        self.gridLayout_13.addWidget(self.bt_reset_4, 0, 2, 2, 1)
        self.label_19 = QtWidgets.QLabel(self.rn_layout_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_19.setFont(font)
        self.label_19.setText("Name Fixer")
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_13.addWidget(self.label_19, 0, 0, 1, 2)
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setContentsMargins(-1, 15, -1, 15)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_60 = QtWidgets.QLabel(self.rn_layout_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_60.setFont(font)
        self.label_60.setToolTip("<html><head/><body><p>Here, you can set a <span style=\" font-weight:600;\">prefix</span> for every files.</p></body></html>")
        self.label_60.setText("Prefix : ")
        self.label_60.setObjectName("label_60")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_60)
        self.rn_4_input_1 = QtWidgets.QLineEdit(self.rn_layout_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.rn_4_input_1.setFont(font)
        self.rn_4_input_1.setPlaceholderText("Text")
        self.rn_4_input_1.setObjectName("rn_4_input_1")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.rn_4_input_1)
        self.label_61 = QtWidgets.QLabel(self.rn_layout_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_61.setFont(font)
        self.label_61.setToolTip("<html><head/><body><p>Here, you can set a <span style=\" font-weight:600;\">suffix</span> for every files.</p></body></html>")
        self.label_61.setText("Suffix :")
        self.label_61.setObjectName("label_61")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_61)
        self.rn_4_input_2 = QtWidgets.QLineEdit(self.rn_layout_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.rn_4_input_2.setFont(font)
        self.rn_4_input_2.setPlaceholderText("Text")
        self.rn_4_input_2.setObjectName("rn_4_input_2")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.rn_4_input_2)
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_38 = QtWidgets.QLabel(self.rn_layout_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_38.setFont(font)
        self.label_38.setToolTip("<html><head/><body><p>If it is <span style=\" font-weight:600;\">checked</span>, then the <span style=\" font-weight:600;\">extension</span> of the fille will remain <span style=\" font-weight:600;\">unchanged</span>.</p></body></html>")
        self.label_38.setText("Don\'t Change extension : ")
        self.label_38.setObjectName("label_38")
        self.gridLayout_15.addWidget(self.label_38, 0, 0, 1, 1)
        self.rn_4_input_3 = QtWidgets.QCheckBox(self.rn_layout_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rn_4_input_3.sizePolicy().hasHeightForWidth())
        self.rn_4_input_3.setSizePolicy(sizePolicy)
        self.rn_4_input_3.setText("")
        self.rn_4_input_3.setChecked(True)
        self.rn_4_input_3.setObjectName("rn_4_input_3")
        self.gridLayout_15.addWidget(self.rn_4_input_3, 0, 1, 1, 1)
        self.formLayout_4.setLayout(2, QtWidgets.QFormLayout.SpanningRole, self.gridLayout_15)
        self.gridLayout_25 = QtWidgets.QGridLayout()
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.rn_4_input_4 = QtWidgets.QLineEdit(self.rn_layout_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.rn_4_input_4.setFont(font)
        self.rn_4_input_4.setPlaceholderText("Old")
        self.rn_4_input_4.setObjectName("rn_4_input_4")
        self.gridLayout_25.addWidget(self.rn_4_input_4, 0, 1, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.rn_layout_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_34.setFont(font)
        self.label_34.setToolTip("")
        self.label_34.setText("Replace : ")
        self.label_34.setObjectName("label_34")
        self.gridLayout_25.addWidget(self.label_34, 0, 0, 1, 1)
        self.rn_4_input_5 = QtWidgets.QLineEdit(self.rn_layout_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.rn_4_input_5.setFont(font)
        self.rn_4_input_5.setPlaceholderText("New")
        self.rn_4_input_5.setObjectName("rn_4_input_5")
        self.gridLayout_25.addWidget(self.rn_4_input_5, 0, 2, 1, 1)
        self.formLayout_4.setLayout(3, QtWidgets.QFormLayout.SpanningRole, self.gridLayout_25)
        self.gridLayout_30 = QtWidgets.QGridLayout()
        self.gridLayout_30.setObjectName("gridLayout_30")
        self.label_58 = QtWidgets.QLabel(self.rn_layout_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_58.setFont(font)
        self.label_58.setToolTip("")
        self.label_58.setText("Replace Range : ")
        self.label_58.setObjectName("label_58")
        self.gridLayout_30.addWidget(self.label_58, 0, 0, 1, 1)
        self.rn_4_input_7 = QtWidgets.QLineEdit(self.rn_layout_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rn_4_input_7.sizePolicy().hasHeightForWidth())
        self.rn_4_input_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.rn_4_input_7.setFont(font)
        self.rn_4_input_7.setPlaceholderText("Start")
        self.rn_4_input_7.setObjectName("rn_4_input_7")
        self.gridLayout_30.addWidget(self.rn_4_input_7, 0, 2, 1, 1)
        self.rn_4_input_8 = QtWidgets.QLineEdit(self.rn_layout_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rn_4_input_8.sizePolicy().hasHeightForWidth())
        self.rn_4_input_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.rn_4_input_8.setFont(font)
        self.rn_4_input_8.setPlaceholderText("End")
        self.rn_4_input_8.setObjectName("rn_4_input_8")
        self.gridLayout_30.addWidget(self.rn_4_input_8, 0, 3, 1, 1)
        self.rn_4_input_6 = QtWidgets.QLineEdit(self.rn_layout_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.rn_4_input_6.setFont(font)
        self.rn_4_input_6.setPlaceholderText("Text")
        self.rn_4_input_6.setObjectName("rn_4_input_6")
        self.gridLayout_30.addWidget(self.rn_4_input_6, 0, 1, 1, 1)
        self.formLayout_4.setLayout(4, QtWidgets.QFormLayout.SpanningRole, self.gridLayout_30)
        self.gridLayout_33 = QtWidgets.QGridLayout()
        self.gridLayout_33.setObjectName("gridLayout_33")
        self.label_33 = QtWidgets.QLabel(self.rn_layout_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_33.setFont(font)
        self.label_33.setToolTip("")
        self.label_33.setText("Remove : ")
        self.label_33.setObjectName("label_33")
        self.gridLayout_33.addWidget(self.label_33, 0, 0, 1, 1)
        self.rn_4_input_9 = QtWidgets.QLineEdit(self.rn_layout_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.rn_4_input_9.setFont(font)
        self.rn_4_input_9.setPlaceholderText("Text")
        self.rn_4_input_9.setObjectName("rn_4_input_9")
        self.gridLayout_33.addWidget(self.rn_4_input_9, 0, 1, 1, 1)
        self.formLayout_4.setLayout(5, QtWidgets.QFormLayout.SpanningRole, self.gridLayout_33)
        self.gridLayout_28 = QtWidgets.QGridLayout()
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.rn_4_input_10 = QtWidgets.QComboBox(self.rn_layout_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rn_4_input_10.setFont(font)
        self.rn_4_input_10.setCurrentText("Before")
        self.rn_4_input_10.setObjectName("rn_4_input_10")
        self.rn_4_input_10.addItem("")
        self.rn_4_input_10.setItemText(0, "Before")
        self.rn_4_input_10.addItem("")
        self.rn_4_input_10.setItemText(1, "After")
        self.gridLayout_28.addWidget(self.rn_4_input_10, 0, 1, 1, 1)
        self.rn_4_input_12 = QtWidgets.QLineEdit(self.rn_layout_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.rn_4_input_12.setFont(font)
        self.rn_4_input_12.setPlaceholderText("Number")
        self.rn_4_input_12.setObjectName("rn_4_input_12")
        self.gridLayout_28.addWidget(self.rn_4_input_12, 0, 3, 1, 1)
        self.rn_4_input_11 = QtWidgets.QLineEdit(self.rn_layout_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.rn_4_input_11.setFont(font)
        self.rn_4_input_11.setPlaceholderText("Old")
        self.rn_4_input_11.setObjectName("rn_4_input_11")
        self.gridLayout_28.addWidget(self.rn_4_input_11, 0, 2, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.rn_layout_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_40.setFont(font)
        self.label_40.setToolTip("")
        self.label_40.setText("Remove : ")
        self.label_40.setObjectName("label_40")
        self.gridLayout_28.addWidget(self.label_40, 0, 0, 1, 1)
        self.formLayout_4.setLayout(6, QtWidgets.QFormLayout.SpanningRole, self.gridLayout_28)
        self.gridLayout_26 = QtWidgets.QGridLayout()
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.label_39 = QtWidgets.QLabel(self.rn_layout_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_39.setFont(font)
        self.label_39.setToolTip("")
        self.label_39.setText("Remove Range : ")
        self.label_39.setObjectName("label_39")
        self.gridLayout_26.addWidget(self.label_39, 0, 0, 1, 1)
        self.rn_4_input_13 = QtWidgets.QLineEdit(self.rn_layout_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.rn_4_input_13.setFont(font)
        self.rn_4_input_13.setPlaceholderText("Start")
        self.rn_4_input_13.setObjectName("rn_4_input_13")
        self.gridLayout_26.addWidget(self.rn_4_input_13, 0, 2, 1, 1)
        self.rn_4_input_14 = QtWidgets.QLineEdit(self.rn_layout_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.rn_4_input_14.setFont(font)
        self.rn_4_input_14.setPlaceholderText("End")
        self.rn_4_input_14.setObjectName("rn_4_input_14")
        self.gridLayout_26.addWidget(self.rn_4_input_14, 0, 3, 1, 1)
        self.formLayout_4.setLayout(7, QtWidgets.QFormLayout.SpanningRole, self.gridLayout_26)
        self.gridLayout_27 = QtWidgets.QGridLayout()
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.rn_4_input_15 = QtWidgets.QLineEdit(self.rn_layout_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.rn_4_input_15.setFont(font)
        self.rn_4_input_15.setPlaceholderText("Text")
        self.rn_4_input_15.setObjectName("rn_4_input_15")
        self.gridLayout_27.addWidget(self.rn_4_input_15, 0, 1, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.rn_layout_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_45.setFont(font)
        self.label_45.setToolTip("")
        self.label_45.setText("Add Text : ")
        self.label_45.setObjectName("label_45")
        self.gridLayout_27.addWidget(self.label_45, 0, 0, 1, 1)
        self.rn_4_input_16 = QtWidgets.QLineEdit(self.rn_layout_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rn_4_input_16.sizePolicy().hasHeightForWidth())
        self.rn_4_input_16.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.rn_4_input_16.setFont(font)
        self.rn_4_input_16.setPlaceholderText("Index")
        self.rn_4_input_16.setObjectName("rn_4_input_16")
        self.gridLayout_27.addWidget(self.rn_4_input_16, 0, 2, 1, 1)
        self.formLayout_4.setLayout(8, QtWidgets.QFormLayout.SpanningRole, self.gridLayout_27)
        self.gridLayout_34 = QtWidgets.QGridLayout()
        self.gridLayout_34.setObjectName("gridLayout_34")
        self.rn_4_input_17 = QtWidgets.QComboBox(self.rn_layout_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rn_4_input_17.setFont(font)
        self.rn_4_input_17.setCurrentText("Before")
        self.rn_4_input_17.setObjectName("rn_4_input_17")
        self.rn_4_input_17.addItem("")
        self.rn_4_input_17.setItemText(0, "Before")
        self.rn_4_input_17.addItem("")
        self.rn_4_input_17.setItemText(1, "After")
        self.gridLayout_34.addWidget(self.rn_4_input_17, 0, 1, 1, 1)
        self.rn_4_input_19 = QtWidgets.QLineEdit(self.rn_layout_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.rn_4_input_19.setFont(font)
        self.rn_4_input_19.setPlaceholderText("Text")
        self.rn_4_input_19.setObjectName("rn_4_input_19")
        self.gridLayout_34.addWidget(self.rn_4_input_19, 0, 3, 1, 1)
        self.rn_4_input_18 = QtWidgets.QLineEdit(self.rn_layout_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.rn_4_input_18.setFont(font)
        self.rn_4_input_18.setPlaceholderText("Old")
        self.rn_4_input_18.setObjectName("rn_4_input_18")
        self.gridLayout_34.addWidget(self.rn_4_input_18, 0, 2, 1, 1)
        self.label_66 = QtWidgets.QLabel(self.rn_layout_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_66.setFont(font)
        self.label_66.setToolTip("")
        self.label_66.setText("Add Text: ")
        self.label_66.setObjectName("label_66")
        self.gridLayout_34.addWidget(self.label_66, 0, 0, 1, 1)
        self.formLayout_4.setLayout(9, QtWidgets.QFormLayout.SpanningRole, self.gridLayout_34)
        self.gridLayout_31 = QtWidgets.QGridLayout()
        self.gridLayout_31.setObjectName("gridLayout_31")
        self.rn_4_input_20 = QtWidgets.QLineEdit(self.rn_layout_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.rn_4_input_20.setFont(font)
        self.rn_4_input_20.setPlaceholderText("New Position")
        self.rn_4_input_20.setObjectName("rn_4_input_20")
        self.gridLayout_31.addWidget(self.rn_4_input_20, 0, 1, 1, 1)
        self.label_59 = QtWidgets.QLabel(self.rn_layout_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_59.setFont(font)
        self.label_59.setToolTip("")
        self.label_59.setText("Copy Text : ")
        self.label_59.setObjectName("label_59")
        self.gridLayout_31.addWidget(self.label_59, 0, 0, 1, 1)
        self.rn_4_input_21 = QtWidgets.QLineEdit(self.rn_layout_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rn_4_input_21.sizePolicy().hasHeightForWidth())
        self.rn_4_input_21.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.rn_4_input_21.setFont(font)
        self.rn_4_input_21.setPlaceholderText("Old Start Index")
        self.rn_4_input_21.setObjectName("rn_4_input_21")
        self.gridLayout_31.addWidget(self.rn_4_input_21, 0, 2, 1, 1)
        self.rn_4_input_22 = QtWidgets.QLineEdit(self.rn_layout_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rn_4_input_22.sizePolicy().hasHeightForWidth())
        self.rn_4_input_22.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.rn_4_input_22.setFont(font)
        self.rn_4_input_22.setPlaceholderText("Old End Index")
        self.rn_4_input_22.setObjectName("rn_4_input_22")
        self.gridLayout_31.addWidget(self.rn_4_input_22, 0, 3, 1, 1)
        self.formLayout_4.setLayout(10, QtWidgets.QFormLayout.SpanningRole, self.gridLayout_31)
        self.label_62 = QtWidgets.QLabel(self.rn_layout_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_62.setFont(font)
        self.label_62.setToolTip("<html><head/><body><p>Here, you can <span style=\" font-weight:600;\">specify</span> what to do when we get <span style=\" font-weight:600;\">errors</span>. <span style=\" font-weight:600;\">Ex:</span> index not found.</p></body></html>")
        self.label_62.setText("On getting error : ")
        self.label_62.setObjectName("label_62")
        self.formLayout_4.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_62)
        self.rn_4_input_23 = QtWidgets.QComboBox(self.rn_layout_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rn_4_input_23.setFont(font)
        self.rn_4_input_23.setCurrentText("Skip that file")
        self.rn_4_input_23.setObjectName("rn_4_input_23")
        self.rn_4_input_23.addItem("")
        self.rn_4_input_23.setItemText(0, "Skip that file")
        self.rn_4_input_23.addItem("")
        self.rn_4_input_23.setItemText(1, "Skip that step")
        self.rn_4_input_23.addItem("")
        self.rn_4_input_23.setItemText(2, "Print error and continue")
        self.rn_4_input_23.addItem("")
        self.rn_4_input_23.setItemText(3, "Print error and stop renaming")
        self.formLayout_4.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.rn_4_input_23)
        self.gridLayout_13.addLayout(self.formLayout_4, 2, 0, 1, 3)
        self.gridLayout_13.setRowStretch(0, 1)
        self.gridLayout_14.addWidget(self.rn_layout_4, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_4)
        self.gridLayout.addWidget(self.stackedWidget, 5, 0, 1, 1)
        self.main_grid.addWidget(self.main_layout, 0, 1, 1, 1)
        self.main_grid.setColumnStretch(0, 2)
        self.main_grid.setColumnStretch(1, 5)
        self.horizontalLayout.addLayout(self.main_grid)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 581, 21))
        self.menubar.setObjectName("menubar")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setTitle("About")
        self.menuAbout.setObjectName("menuAbout")
        self.menuTool = QtWidgets.QMenu(self.menubar)
        self.menuTool.setTitle("Tool")
        self.menuTool.setObjectName("menuTool")
        self.menuRenameIt = QtWidgets.QMenu(self.menubar)
        self.menuRenameIt.setTitle("RenameIt")
        self.menuRenameIt.setObjectName("menuRenameIt")
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setWindowTitle("Toolbar")
        self.toolBar.setMovable(False)
        self.toolBar.setIconSize(QtCore.QSize(28, 28))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionReset_1 = QtWidgets.QAction(MainWindow)
        self.actionReset_1.setText("Reset")
        self.actionReset_1.setObjectName("actionReset_1")
        self.actionExit_1 = QtWidgets.QAction(MainWindow)
        self.actionExit_1.setText("Exit")
        self.actionExit_1.setObjectName("actionExit_1")
        self.actionAbout_the_Author = QtWidgets.QAction(MainWindow)
        self.actionAbout_the_Author.setText("About the Author")
        self.actionAbout_the_Author.setObjectName("actionAbout_the_Author")
        self.actionAdd = QtWidgets.QAction(MainWindow)
        self.actionAdd.setText("Add")
        self.actionAdd.setToolTip("Add a Folder")
        self.actionAdd.setObjectName("actionAdd")
        self.actionClear = QtWidgets.QAction(MainWindow)
        self.actionClear.setText("Clear All")
        self.actionClear.setToolTip("Clear all selected folders")
        self.actionClear.setObjectName("actionClear")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setText("Exit")
        self.actionExit.setObjectName("actionExit")
        self.actionReset = QtWidgets.QAction(MainWindow)
        self.actionReset.setText("Reset")
        self.actionReset.setObjectName("actionReset")
        self.actionAdd_1 = QtWidgets.QAction(MainWindow)
        self.actionAdd_1.setText("Add a Folder")
        self.actionAdd_1.setObjectName("actionAdd_1")
        self.actionClear_1 = QtWidgets.QAction(MainWindow)
        self.actionClear_1.setText("Clear All Folders")
        self.actionClear_1.setObjectName("actionClear_1")
        self.actionAdd_Multiple_Folder = QtWidgets.QAction(MainWindow)
        self.actionAdd_Multiple_Folder.setText("Add Multiple Folder")
        self.actionAdd_Multiple_Folder.setObjectName("actionAdd_Multiple_Folder")
        self.menuAbout.addAction(self.actionAbout_the_Author)
        self.menuTool.addAction(self.actionAdd_1)
        self.menuTool.addAction(self.actionAdd_Multiple_Folder)
        self.menuTool.addSeparator()
        self.menuTool.addAction(self.actionClear_1)
        self.menuRenameIt.addAction(self.actionReset_1)
        self.menuRenameIt.addSeparator()
        self.menuRenameIt.addAction(self.actionExit_1)
        self.menubar.addAction(self.menuRenameIt.menuAction())
        self.menubar.addAction(self.menuTool.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionAdd)
        self.toolBar.addAction(self.actionClear)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionReset)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionExit)

        self.stackedWidget.setCurrentIndex(0)
        self.side_input_2.toggled['bool'].connect(self.widget_0_1.setEnabled)
        self.side_input_8.toggled['bool'].connect(self.widget_0_2.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.side_input_1, self.side_input_2)
        MainWindow.setTabOrder(self.side_input_2, self.side_input_3)
        MainWindow.setTabOrder(self.side_input_3, self.side_input_4)
        MainWindow.setTabOrder(self.side_input_4, self.side_input_5)
        MainWindow.setTabOrder(self.side_input_5, self.side_input_6)
        MainWindow.setTabOrder(self.side_input_6, self.side_input_7)
        MainWindow.setTabOrder(self.side_input_7, self.side_input_8)
        MainWindow.setTabOrder(self.side_input_8, self.side_input_9)
        MainWindow.setTabOrder(self.side_input_9, self.side_input_10)
        MainWindow.setTabOrder(self.side_input_10, self.side_input_11)
        MainWindow.setTabOrder(self.side_input_11, self.side_input_12)
        MainWindow.setTabOrder(self.side_input_12, self.side_input_13)
        MainWindow.setTabOrder(self.side_input_13, self.bt_main_menu)
        MainWindow.setTabOrder(self.bt_main_menu, self.bt_menu_1)
        MainWindow.setTabOrder(self.bt_menu_1, self.bt_menu_2)
        MainWindow.setTabOrder(self.bt_menu_2, self.bt_menu_3)
        MainWindow.setTabOrder(self.bt_menu_3, self.bt_menu_4)
        MainWindow.setTabOrder(self.bt_menu_4, self.bt_reset_1)
        MainWindow.setTabOrder(self.bt_reset_1, self.rn_1_input_1)
        MainWindow.setTabOrder(self.rn_1_input_1, self.rn_1_input_2)
        MainWindow.setTabOrder(self.rn_1_input_2, self.bt_rename_1)
        MainWindow.setTabOrder(self.bt_rename_1, self.bt_reset_2)
        MainWindow.setTabOrder(self.bt_reset_2, self.rn_2_input_1)
        MainWindow.setTabOrder(self.rn_2_input_1, self.rn_2_input_2)
        MainWindow.setTabOrder(self.rn_2_input_2, self.rn_2_input_3)
        MainWindow.setTabOrder(self.rn_2_input_3, self.bt_rename_2)
        MainWindow.setTabOrder(self.bt_rename_2, self.bt_reset_3)
        MainWindow.setTabOrder(self.bt_reset_3, self.rn_3_input_1)
        MainWindow.setTabOrder(self.rn_3_input_1, self.bt_help_3_1)
        MainWindow.setTabOrder(self.bt_help_3_1, self.rn_3_input_2)
        MainWindow.setTabOrder(self.rn_3_input_2, self.rn_3_input_3)
        MainWindow.setTabOrder(self.rn_3_input_3, self.rn_3_input_4)
        MainWindow.setTabOrder(self.rn_3_input_4, self.rn_3_input_5)
        MainWindow.setTabOrder(self.rn_3_input_5, self.rn_3_input_6)
        MainWindow.setTabOrder(self.rn_3_input_6, self.rn_3_input_7)
        MainWindow.setTabOrder(self.rn_3_input_7, self.rn_3_input_8)
        MainWindow.setTabOrder(self.rn_3_input_8, self.bt_help_3_2)
        MainWindow.setTabOrder(self.bt_help_3_2, self.rn_3_input_9)
        MainWindow.setTabOrder(self.rn_3_input_9, self.bt_help_3_3)
        MainWindow.setTabOrder(self.bt_help_3_3, self.bt_rename_3)
        MainWindow.setTabOrder(self.bt_rename_3, self.bt_reset_4)
        MainWindow.setTabOrder(self.bt_reset_4, self.rn_4_input_1)
        MainWindow.setTabOrder(self.rn_4_input_1, self.rn_4_input_2)
        MainWindow.setTabOrder(self.rn_4_input_2, self.rn_4_input_3)
        MainWindow.setTabOrder(self.rn_4_input_3, self.rn_4_input_4)
        MainWindow.setTabOrder(self.rn_4_input_4, self.rn_4_input_5)
        MainWindow.setTabOrder(self.rn_4_input_5, self.rn_4_input_6)
        MainWindow.setTabOrder(self.rn_4_input_6, self.rn_4_input_7)
        MainWindow.setTabOrder(self.rn_4_input_7, self.rn_4_input_8)
        MainWindow.setTabOrder(self.rn_4_input_8, self.rn_4_input_9)
        MainWindow.setTabOrder(self.rn_4_input_9, self.rn_4_input_10)
        MainWindow.setTabOrder(self.rn_4_input_10, self.rn_4_input_11)
        MainWindow.setTabOrder(self.rn_4_input_11, self.rn_4_input_12)
        MainWindow.setTabOrder(self.rn_4_input_12, self.rn_4_input_13)
        MainWindow.setTabOrder(self.rn_4_input_13, self.rn_4_input_14)
        MainWindow.setTabOrder(self.rn_4_input_14, self.rn_4_input_15)
        MainWindow.setTabOrder(self.rn_4_input_15, self.rn_4_input_16)
        MainWindow.setTabOrder(self.rn_4_input_16, self.rn_4_input_17)
        MainWindow.setTabOrder(self.rn_4_input_17, self.rn_4_input_18)
        MainWindow.setTabOrder(self.rn_4_input_18, self.rn_4_input_19)
        MainWindow.setTabOrder(self.rn_4_input_19, self.rn_4_input_20)
        MainWindow.setTabOrder(self.rn_4_input_20, self.rn_4_input_21)
        MainWindow.setTabOrder(self.rn_4_input_21, self.rn_4_input_22)
        MainWindow.setTabOrder(self.rn_4_input_22, self.rn_4_input_23)
        MainWindow.setTabOrder(self.rn_4_input_23, self.bt_rename_4)
